/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#006b5f',
        'on-primary': '#ffffff',
        'primary-container': '#00a896',
        'on-primary-container': '#00352e',
        secondary: '#735c00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed65b',
        'on-secondary-container': '#745c00',
        tertiary: '#426465',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#799c9d',
        'on-tertiary-container': '#0f3335',
        background: '#f9f9fc',
        surface: '#f9f9fc',
        'on-surface': '#1a1c1e',
        'on-surface-variant': '#3c4946',
        outline: '#6c7a76',
        'outline-variant': '#bbcac5',
        error: '#ba1a1a',
        'surface-variant': '#e2e2e5',
        'surface-container': '#eeeef0',
        'surface-container-low': '#f3f3f6',
        'surface-container-high': '#e8e8ea',
        'surface-container-highest': '#e2e2e5',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed': '#ffe088',
        'secondary-fixed-dim': '#e9c349',
        'on-secondary-fixed': '#241a00',
      },
      spacing: {
        base: '8px',
        'container-padding': '24px',
        gutter: '16px',
        'card-gap': '12px',
        'section-margin': '48px',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display': ['48px', { lineHeight: '1.2', fontWeight: '800', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700', letterSpacing: '-0.01em' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['12px', { lineHeight: '16px', fontWeight: '700', letterSpacing: '0.05em' }],
        'label-sm': ['10px', { lineHeight: '14px', fontWeight: '600' }],
      }
    },
  },
  plugins: [],
}
